name: Go
on: [push, pull_request]

jobs:

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        go: ['1.20.x', '1.21.x']

    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          stable: '!contains(${{ matrix.go }}, "beta") && !contains(${{ matrix.go }}, "rc")'
          go-version: ${{ matrix.go }}
        id: go

      - name: Vet
        run: go vet -v ./...
        
      - name: Test
        env:
          LANG: en
        run: go test -v -coverprofile='coverage.txt' -covermode=atomic ./...

      - name: Upload Coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
